# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

# the name is for visual purposes only
name: car-rental-maven-publish

on:
  push:
    branches:
      - main

jobs:
  build:
        runs-on: ubuntu-latest
        permissions:
          contents: read
          packages: write
        steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'adopt'
            java-version: '17'
        - name: Build with Maven
          run: mvn -B package -DskipTests --file CarRentalManagementSystem/pom.xml
        - name: Publish to GitHub Packages
          run: mvn deploy -s .github/settings.xml
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
